# Default values for discovery.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: ghcr.io/wasfree/discovery
  pullPolicy: IfNotPresent
  tag: v0.1.23

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

podAnnotations: {}

podSecurityContext:
  sysctls:
  - name: net.ipv4.ping_group_range
    value: 0   2147483647
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

service:
  type: ClusterIP

serviceMonitor:
  enabled: true
  name: metrics
  port: 9092
  path: /metrics
  interval: 10s
  scrapeTimeout: 10s
  scheme: http

discovery:
  loglevel: "info"
  ports: "80,443"
  workers: 10
  timeout: 10s
  rescan: 0s
  cidrsFilepath: "./data/test.txt"
  postgresql:
    database: "discovery"
    user: "pguser"
    host: "postgres"
    # connMaxLifetime: "1h"
    # maxIdleConns: "25"
    # maxOpenConns: "100"
  externalFiles:
    enabled: false
    # cidrs:
    #   test.txt:
    #     - 1.0.0.0/24
    #     - 1.0.1.0/24
    #     - 1.0.2.0/23
    #     - 1.0.4.0/22
    #     - 1.0.8.0/21

postgresql:
  enabled: true
  auth:
    username: "pguser"
    database: "discovery"
    existingSecret: "postgres-secrets"
    secretKeys:
      adminPasswordKey: postgres-password
      userPasswordKey: password

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}
