apiVersion: v1
kind: Service
metadata:
  name: {{ include "discovery.fullname" . }}
  labels:
    {{- include "discovery.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.serviceMonitor.port }}
      targetPort: {{ .Values.serviceMonitor.name }}
      protocol: TCP
      name: {{ .Values.serviceMonitor.name }}
  selector:
    {{- include "discovery.selectorLabels" . | nindent 4 }}
